# Run the courts scraper

name: Scrape courts

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: bash run-perl-scrape.sh
      # commit
      - uses: EndBug/add-and-commit@v9 
        with:
          add: filings.sqlite
          author_name: GH Actions
          author_email: GHActions@example.com
          commit: --signoff
          message: Github Actions ran courtbot
          push: true
